import React, { useState } from 'react';
import type { AlertItem } from '../types';

interface AlertsTriageViewProps {
  alerts: AlertItem[];
  fetchAlerts: () => void;
  setSelectedAlertModal: (alert: AlertItem) => void;
  handleAcknowledgeAlert: (alertId: string, e?: React.MouseEvent) => void;
}

export const AlertsTriageView: React.FC<AlertsTriageViewProps> = ({
  alerts,
  fetchAlerts,
  setSelectedAlertModal,
  handleAcknowledgeAlert,
}) => {
  const [filterTab, setFilterTab] = useState<'active' | 'acknowledged' | 'all'>('active');

  const handleClearAll = async () => {
    if (!window.confirm("Are you sure you want to empty the clinical alert section?")) return;
    try {
      const res = await fetch('http://localhost:8000/api/alerts/clear', { method: 'POST' });
      if (res.ok) {
        fetchAlerts();
      }
    } catch (e) {
      console.error("Clear alerts error:", e);
    }
  };

  const filteredAlerts = alerts.filter(a => {
    if (filterTab === 'active') return a.status !== 'acknowledged';
    if (filterTab === 'acknowledged') return a.status === 'acknowledged';
    return true;
  });

  return (
    <div className="flex-1 overflow-y-auto p-8 pb-20 bg-slate-900">
      <div className="max-w-5xl mx-auto">
        
        {/* HEADER */}
        <div className="flex items-center justify-between mb-8 pb-6 border-b border-slate-800">
          <div>
            <h2 className="text-2xl font-bold text-slate-100 flex items-center gap-3">
              <span className="p-2 bg-red-500/10 border border-red-500/20 text-red-400 rounded-xl text-lg">🚨</span>
              Clinical Alerts Triage Dashboard
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Risk-prioritized alerts generated by automated multi-document delta comparison & baseline anomaly scanning.
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleClearAll}
              className="px-3 py-2 bg-red-950/40 hover:bg-red-900/60 text-red-300 text-xs font-medium rounded-xl border border-red-800/60 transition-colors"
            >
              🗑️ Clear All Alerts
            </button>
            <button
              onClick={fetchAlerts}
              className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs rounded-xl border border-slate-700 transition-colors"
            >
              🔄 Refresh Alerts
            </button>
          </div>
        </div>

        {/* TAB FILTER CONTROLS */}
        <div className="flex items-center gap-2 mb-6">
          <button
            onClick={() => setFilterTab('active')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
              filterTab === 'active'
                ? 'bg-red-500 text-white shadow-md shadow-red-950/40'
                : 'bg-slate-800 text-slate-400 hover:text-slate-200 border border-slate-700'
            }`}
          >
            Active Triage ({alerts.filter(a => a.status !== 'acknowledged').length})
          </button>
          <button
            onClick={() => setFilterTab('acknowledged')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
              filterTab === 'acknowledged'
                ? 'bg-emerald-600 text-white shadow-md shadow-emerald-950/40'
                : 'bg-slate-800 text-slate-400 hover:text-slate-200 border border-slate-700'
            }`}
          >
            Acknowledged History ({alerts.filter(a => a.status === 'acknowledged').length})
          </button>
          <button
            onClick={() => setFilterTab('all')}
            className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
              filterTab === 'all'
                ? 'bg-blue-600 text-white shadow-md shadow-blue-950/40'
                : 'bg-slate-800 text-slate-400 hover:text-slate-200 border border-slate-700'
            }`}
          >
            All Logs ({alerts.length})
          </button>
        </div>

        {/* ALERTS LIST */}
        {filteredAlerts.length === 0 ? (
          <div className="bg-slate-800/50 border border-slate-700/50 rounded-2xl p-12 text-center text-slate-400">
            <span className="text-4xl mb-3 block">✅</span>
            <h3 className="text-lg font-semibold text-slate-200">No Alerts in this View</h3>
            <p className="text-xs text-slate-400 mt-1">All patient records are clean and within stable parameters.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {filteredAlerts.map((alert) => {
              const isAcknowledged = alert.status === 'acknowledged';
              const isHigh = alert.severity_level === 'high' && !isAcknowledged;

              return (
                <div
                  key={alert.alert_id}
                  onClick={() => setSelectedAlertModal(alert)}
                  className={`p-5 rounded-2xl border transition-all cursor-pointer flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-lg ${
                    isAcknowledged
                      ? 'bg-slate-900/60 border-emerald-500/30 hover:border-emerald-500/60'
                      : isHigh
                      ? 'bg-red-950/20 border-red-500/40 hover:border-red-500/80 shadow-red-950/20'
                      : 'bg-amber-950/20 border-amber-500/40 hover:border-amber-500/80'
                  }`}
                >
                  <div className="flex items-start gap-4 flex-1">
                    <div className={`w-3 h-3 rounded-full mt-1.5 flex-shrink-0 ${
                      isAcknowledged ? 'bg-emerald-500' : isHigh ? 'bg-red-500 animate-pulse' : 'bg-amber-500'
                    }`} />
                    
                    <div>
                      <div className="flex items-center gap-3 mb-1">
                        <h3 className="font-bold text-slate-100 text-base">{alert.patient_name}</h3>
                        <span className="px-2 py-0.5 bg-slate-800 text-slate-400 text-xs rounded-md border border-slate-700 font-mono">
                          ID: {alert.patient_id}
                        </span>
                        <span className="text-xs text-slate-400">Age: {alert.age}</span>
                        <span className={`px-2 py-0.5 text-xs font-semibold rounded-full border uppercase ${
                          isAcknowledged
                            ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                            : isHigh
                            ? 'bg-red-500/10 text-red-400 border-red-500/30'
                            : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
                        }`}>
                          {isAcknowledged ? 'Acknowledged' : `${alert.severity_level} Risk (${alert.risk_score})`}
                        </span>
                      </div>

                      <p className="text-sm font-semibold text-slate-200">{alert.title}</p>
                      <p className="text-xs text-slate-400 line-clamp-2 mt-1">{alert.ai_summary}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-3 w-full md:w-auto justify-end">
                    <button
                      onClick={(e) => { e.stopPropagation(); setSelectedAlertModal(alert); }}
                      className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs rounded-xl border border-slate-700 transition-colors"
                    >
                      View Summary →
                    </button>

                    {isAcknowledged ? (
                      <span className="px-4 py-2 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 text-xs rounded-xl font-bold flex items-center gap-1.5">
                        <span>✓</span> Acknowledged
                      </span>
                    ) : (
                      <button
                        onClick={(e) => handleAcknowledgeAlert(alert.alert_id, e)}
                        className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold rounded-xl shadow-md transition-all border border-emerald-500"
                      >
                        Acknowledge
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};
